apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
spec:
  project: default
  source:
    repoURL: 'https://github.com/herpriz2/niture.git'
    targetRevision: HEAD
    path: '/niture/hello.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
